[book]
authors = ["Sam Liu"]
language = "en"
multilingual = false
src = "src"
title = "ontouchstart.pages.dev"

[output]
[output.html]
git-repository-url = "https://github.com/ontouchstart/cloudflare-page"
