[book]
authors = ["Sam Liu"]
language = "en"
multilingual = false
src = "src"
title = "ontouchstart.pages.dev"

[build]
build-dir = "docs"

[output]
[output.html]
git-repository-url = "https://github.com/ontouchstart/cloudflare-page"

[output.html.playground]
editable = true
line-numbers = true