[book]
authors = ["Sam Liu"]
language = "en"
multilingual = false
src = "src"
title = "ontouchstart.pages.dev"
[preprocessor]
[preprocessor.katex]
macros = "katex/macros.txt"

[preprocessor.mermaid]
command = "mdbook-mermaid"
[output]
[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]
