build: empty_module \
	return_module \
	add_only_module \
	call_js_func_module

empty_module:
	make -C rust/empty_module

return_module:
	make -C rust/return_module

add_only_module:
	make -C rust/add_only_module

call_js_func_module:
	make -C rust/call_js_func_module

